### ISSUE TITLE
Mixing update() etc. with a live data proxy?

### ISSUE THREAD

**Issue by clibu** [appy-one/acebase#23] opened 2021-03-21 23:44 UTC
From what I'm seeing if you call ``update()`` on a path that has a Proxy then the proxy isn't aware of the update changes.  

Assuming this isn't a bug and is too difficult to resolve that's fine, however the doc's need to boldly point out that you can't mix the two approaches.

**Comment by appy-one** [comment] 2021-03-22 04:22
They should mix perfectly fine, all db changes must update the proxy value

**Comment by clibu** [comment] 2021-03-22 04:51
Good to hear. I'll try and replicate what I was seeing in a small sample app. Might be a day or so.

**Comment by clibu** [comment] 2021-03-23 04:04
Ok my description in the first post wasn't right. The issue is to do with ``onMutation()`` callback calls.

I wrote small Node program and tried various things.  The issue I am able to reproduce in the Browser, but not in the Node code below is this.

Sample 1 - doesn't show the problem, just describes it
````
    const ref = db.ref('test');
    const proxy = await ref.proxy( {} );
    const obj = proxy.value;

    proxy.onMutation( ( mutationSnapshot, isRemoteChange ) => {
        console.log( 'onMutation() path:', mutationSnapshot.ref.path, ', key:', mutationSnapshot.key, ', value:', mutationSnapshot.val() )
    })

    await ref.update( { car: 'Jaguar' } )

    // Somewhere else in the app ...
    // Doesn't fire onMutation() callback. If I change the update() call above to obj.car = .. the callback is called.
    obj.car = 'Jaguar'
````

Sample 2 - delete db if present and run this once. When run again you see behaviour as described.
````
import { AceBase } from 'acebase';

const db = new AceBase( 'debug' /*,  { logLevel: 'verbose' } */ );

db.ready( async () => {
   const ref = db.ref('test');
    const proxy = await ref.proxy( {} );
    const obj = proxy.value;

    proxy.onMutation( ( mutationSnapshot, isRemoteChange ) => {
        console.log( 'onMutation() path:', mutationSnapshot.ref.path, ', key:', mutationSnapshot.key, ', value:', mutationSnapshot.val() )
    })

    // Run app once then repeat with test1 true a few times. They with false to see onMutation()'s
    const test1 = false
    if ( test1 ){
        // Each run alternates mutations value between 'Porsche' and 'Jaguar'
        await ref.update( { car: 'Jaguar' } )
    }else{
        // mutations always has value 'Porsche' and is only called once, should be twice!
        obj.car = 'Jaguar'
    }

    obj.car = 'Porsche'

});
````

**Comment by clibu** [comment] 2021-03-23 07:35
Small update. In the second example with ``test1 = false`` and:
````
    setTimeout( () => {
        obj.car = 'Porsche'
    }, 0 )  // any delay will do
````
logs both Jaguar and Porsce.

**Comment by appy-one** [comment] 2021-03-23 08:41
Thanks, I'll check!

**Comment by appy-one** [comment] 2021-03-23 14:22
It took some time to investigate, but this is a classic race condition going on here!

Simplifying the code, making it easier to reproduce and analyze the sequence of execution:
```js
const ref = db.ref('test');
const proxy = await ref.proxy({});
const obj = proxy.value;

proxy.onMutation((snapshot, isRemote) => {
    console.log(`${snapshot.ref.path} was updated to ${snapshot.val()} through ${isRemote ? 'ref' : 'proxy'}, previous value was: ${snapshot.previous()}`);
});

// Update value through ref:
await ref.update({ car: 'Jaguar' });

// Update value through proxy:
obj.car = 'Porsche';
```

When the code runs the first time:
1. value of `test/car` in database is `null` (doesn't exist)
2. proxy values loads, `obj.car === undefined`
3. car is updated to 'Jaguar' outside the proxy through `ref.update`: database is updated, mutation events are prepared and scheduled to fire in next tick.
4. Setting `obj.car = 'Porsche'`: proxy schedules a database update in next tick.
5. mutation events for step 3 fire, onMutation callback fires and prints  `"test/car was updated to Jaguar through ref, previous value was: null"`
6. proxy updates the database async, schedules mutation callbacks to fire in next tick.
7. mutation events for step 6 fire, `onMutation` callback fires and prints `"test/car was updated to Porsche through proxy, previous value was: Jaguar"`

Then, when running the 2nd time:
1. value of `test/car` in database is `'Porsche'`
2. proxy value loads, `obj.car === 'Porsche'`
3. car is updated to 'Jaguar' outside the proxy through `ref.update`: database is updated, mutation events are prepared and scheduled to fire in next tick
4. Setting `obj.car = 'Porsche'`: proxy sees this is the current value (it has not received mutation notification yet) so does not schedule database update.
5. mutation events for step 3 fire, proxied car value is updated to 'Jaguar', `onMutation` callback fires and prints `"test/car was updated to Jaguar through ref, previous value was: Porsche"`

Running 3rd time:
1. value of `test/car` in database is `'Jaguar'`
2. proxy value loads, `obj.car === 'Jaguar'`
3. car is updated to 'Jaguar' outside the proxy through `ref.update`: database value does not change so no mutation events are prepared.
4. Setting `obj.car = 'Porsche'`: proxy schedules a database update in next tick.
5. mutation events for step 4 fire, `onMutation` callback fires and prints `"test/car was updated to Porsche through proxy, previous value was: Jaguar"`

Running again after this will repeat 2nd and 3rd time runs. 

In real-world situations this is vitrually impossible to occur, because both updates will have to execute in nearly the same tick, and they both have to 'undo' their respective values. Preventing this will not be possible because of the asynchronous execution of the mutation events. Especially when running over a network connection between an `acebase-client` and `acebase-server`.

Long answer short: mystery solved, it's not a bug!

**Comment by clibu** [comment] 2021-03-23 20:23
OK, that all seems ok. I appreciate how complex all of this is.

Does this also explain the ``test1 = false`` case without the ``setTimeout()`` where only one mutation callback fires?

**Comment by appy-one** [comment] 2021-03-23 21:17
Yes, doing the following will update the db only once because the target value is marked as changed, and the db is updated in the next tick:
```js
obj.car = 'Porsche'; // flags car as changed
obj.car = 'Jaguar'; // Already flagged
// db will be updated once in next tick
```

**Comment by clibu** [comment] 2021-03-24 10:55
Ok, thanks.

**Closed** 2021-03-24 14:55 UTC
